export const mockStudent = {
  id: "student-id-1",
  name: "Test Student",
  email: "student@placetrack.app",
  hashedPassword: "$2b$12$hashedpassword",
  role: "STUDENT" as const,
  branch: "CSE",
  cgpa: 8.5,
  backlogs: 0,
  graduationYear: 2025,
  avatarUrl: null,
  rollNumber: "21CS001",
  phone: null,
  createdAt: new Date("2024-01-01"),
  updatedAt: new Date("2024-01-01"),
};

export const mockCompany = {
  id: "company-id-1",
  name: "Google",
  logoUrl: null,
  website: null,
  sector: "Technology",
  role: "Software Engineer",
  packageLpa: 45.0,
  packageMax: 60.0,
  jobType: "Full-time",
  minCgpa: 8.0,
  maxBacklogs: 0,
  branches: ["CSE", "ECE", "MCA"],
  jdUrl: null,
  description: "Join Google engineering.",
  deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
  driveDate: null,
  status: "OPEN" as const,
  createdById: "coordinator-id-1",
  createdAt: new Date("2024-01-01"),
  updatedAt: new Date("2024-01-01"),
};

export const mockApplication = {
  id: "application-id-1",
  studentId: "student-id-1",
  companyId: "company-id-1",
  stage: "APPLIED" as const,
  notes: null,
  appliedAt: new Date("2024-06-01"),
  updatedAt: new Date("2024-06-01"),
};